name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  convert: ^3.1.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  maplibre_gl: 0.21.0
  url_launcher: ^6.2.6
  flutter_screenutil: ^5.9.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  mobile_scanner: ^6.0.7
  pretty_qr_code: ^3.3.0
  intl: ^0.18.1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  geolocator: ^11.0.0
  notifications: ^3.1.0
  google_fonts: ^5.0.0
  geocoding: ^2.1.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  syncfusion_flutter_pdf: ^29.2.5
  syncfusion_flutter_pdfviewer: ^29.2.5
  gal: ^2.3.1
  flutter_svg: ^2.2.1
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.0
  badges: ^3.1.2
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icpeplogolatest.svg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
